-- Evidence-driven semantic governance (MySQL 8, idempotent).

CREATE TABLE IF NOT EXISTS semantic_governance_policies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    observe_only BOOLEAN NOT NULL DEFAULT TRUE,
    run_after_scan BOOLEAN NOT NULL DEFAULT FALSE,
    exact_row_threshold INT NOT NULL DEFAULT 50000,
    sample_row_limit INT NOT NULL DEFAULT 1000,
    table_timeout_sec INT NOT NULL DEFAULT 3,
    max_tables_per_run INT NOT NULL DEFAULT 5,
    max_run_seconds INT NOT NULL DEFAULT 90,
    review_threshold DOUBLE NOT NULL DEFAULT 0.65,
    high_confidence_threshold DOUBLE NOT NULL DEFAULT 0.90,
    auto_apply_threshold DOUBLE NOT NULL DEFAULT 0.98,
    min_auto_evidence_sources INT NOT NULL DEFAULT 2,
    auto_action_types JSON NOT NULL,
    policy_version VARCHAR(32) NOT NULL DEFAULT 'evidence-v1',
    updated_by VARCHAR(64) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_semantic_governance_policy (workspace_id, datasource_id),
    KEY ix_semantic_governance_policy_workspace (workspace_id),
    KEY ix_semantic_governance_policy_datasource (datasource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_governance_runs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    trigger_type VARCHAR(32) NOT NULL DEFAULT 'manual',
    triggered_by VARCHAR(64) NULL,
    scan_id INT NULL,
    schema_fingerprint VARCHAR(64) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    stage VARCHAR(32) NOT NULL DEFAULT 'queued',
    progress INT NOT NULL DEFAULT 0,
    observe_only BOOLEAN NOT NULL DEFAULT TRUE,
    summary_json JSON NOT NULL,
    budget_json JSON NOT NULL,
    error_message TEXT NULL,
    worker_id VARCHAR(128) NULL,
    run_token VARCHAR(64) NULL,
    lease_expires_at DATETIME NULL,
    heartbeat_at DATETIME NULL,
    attempt INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 2,
    cancel_requested_at DATETIME NULL,
    created_at DATETIME NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    KEY ix_semantic_governance_run_workspace (workspace_id),
    KEY ix_semantic_governance_run_datasource (datasource_id),
    KEY ix_semantic_governance_run_scan (scan_id),
    KEY ix_semantic_governance_run_status (status),
    KEY ix_semantic_governance_run_status_lease (status, lease_expires_at),
    KEY ix_semantic_governance_run_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_column_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    run_id INT NOT NULL,
    table_id INT NOT NULL,
    column_id INT NOT NULL,
    schema_fingerprint VARCHAR(64) NULL,
    profile_status VARCHAR(20) NOT NULL DEFAULT 'complete',
    sample_method VARCHAR(20) NOT NULL DEFAULT 'exact',
    estimated_rows INT NULL,
    sampled_rows INT NOT NULL DEFAULT 0,
    non_null_count INT NOT NULL DEFAULT 0,
    null_ratio DOUBLE NULL,
    distinct_count INT NULL,
    distinct_ratio DOUBLE NULL,
    range_json JSON NOT NULL,
    avg_length DOUBLE NULL,
    pattern_ratios_json JSON NOT NULL,
    error_message TEXT NULL,
    profiled_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    UNIQUE KEY uq_semantic_column_profile_run (run_id, column_id),
    KEY ix_semantic_profile_workspace (workspace_id),
    KEY ix_semantic_profile_datasource (datasource_id),
    KEY ix_semantic_profile_table (table_id),
    KEY ix_semantic_profile_column (column_id),
    KEY ix_semantic_profile_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_evidence_facts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    run_id INT NULL,
    subject_type VARCHAR(32) NOT NULL,
    subject_id INT NULL,
    claim_type VARCHAR(64) NOT NULL,
    claim_key VARCHAR(255) NOT NULL,
    value_json JSON NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_ref VARCHAR(255) NULL,
    direction VARCHAR(16) NOT NULL DEFAULT 'support',
    reliability DOUBLE NOT NULL DEFAULT 0.5,
    strength DOUBLE NOT NULL DEFAULT 1.0,
    fact_fingerprint VARCHAR(64) NOT NULL,
    schema_fingerprint VARCHAR(64) NULL,
    observed_at DATETIME NULL,
    expires_at DATETIME NULL,
    UNIQUE KEY uq_semantic_evidence_fact (workspace_id, datasource_id, fact_fingerprint),
    KEY ix_semantic_evidence_workspace (workspace_id),
    KEY ix_semantic_evidence_datasource (datasource_id),
    KEY ix_semantic_evidence_run (run_id),
    KEY ix_semantic_evidence_subject (subject_type, subject_id),
    KEY ix_semantic_evidence_claim (claim_type),
    KEY ix_semantic_evidence_source (source_type),
    KEY ix_semantic_evidence_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_governance_candidates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    run_id INT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id INT NULL,
    candidate_type VARCHAR(64) NOT NULL,
    candidate_key VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    before_json JSON NOT NULL,
    proposed_patch_json JSON NOT NULL,
    applied_patch_json JSON NOT NULL,
    supporting_evidence_json JSON NOT NULL,
    conflicting_evidence_json JSON NOT NULL,
    evidence_fact_ids JSON NOT NULL,
    source_types JSON NOT NULL,
    score DOUBLE NOT NULL DEFAULT 0,
    score_version VARCHAR(32) NOT NULL DEFAULT 'evidence-v1',
    risk_level VARCHAR(20) NOT NULL DEFAULT 'medium',
    status VARCHAR(24) NOT NULL DEFAULT 'proposed',
    auto_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    deterministic_check_passed BOOLEAN NOT NULL DEFAULT FALSE,
    policy_version VARCHAR(32) NOT NULL DEFAULT 'evidence-v1',
    target_updated_at DATETIME NULL,
    decided_by VARCHAR(64) NULL,
    decision_reason TEXT NULL,
    decided_at DATETIME NULL,
    applied_at DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_semantic_governance_candidate (workspace_id, datasource_id, candidate_key),
    KEY ix_semantic_candidate_workspace (workspace_id),
    KEY ix_semantic_candidate_datasource (datasource_id),
    KEY ix_semantic_candidate_run (run_id),
    KEY ix_semantic_candidate_target (target_type, target_id),
    KEY ix_semantic_candidate_type (candidate_type),
    KEY ix_semantic_candidate_status (status),
    KEY ix_semantic_candidate_risk (risk_level),
    KEY ix_semantic_candidate_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO semantic_governance_policies (
    workspace_id, datasource_id, enabled, observe_only, run_after_scan,
    auto_action_types, created_at, updated_at
)
SELECT workspace_id, id, TRUE, TRUE, TRUE,
       JSON_ARRAY('refresh_evidence', 'supersede_duplicate', 'block_conflict', 'mark_sensitive', 'disable_invalid_asset'),
       NOW(), NOW()
FROM semantic_datasources
ON DUPLICATE KEY UPDATE datasource_id = VALUES(datasource_id);

INSERT IGNORE INTO semantic_governance_candidates (
    workspace_id, datasource_id, run_id, target_type, target_id,
    candidate_type, candidate_key, title, before_json, proposed_patch_json,
    applied_patch_json, supporting_evidence_json, conflicting_evidence_json,
    evidence_fact_ids, source_types, score, score_version, risk_level,
    status, auto_eligible, deterministic_check_passed, policy_version,
    created_at, updated_at
)
SELECT
    workspace_id,
    datasource_id,
    NULL,
    CASE object_type WHEN 'table' THEN 'tables' ELSE 'columns' END,
    object_id,
    'business_semantics',
    SHA2(CONCAT('legacy-suggestion:', id), 256),
    CONCAT('业务语义建议：', suggested_business_name),
    JSON_OBJECT(),
    JSON_OBJECT(
        'business_name', suggested_business_name,
        'description', COALESCE(suggested_description, ''),
        'synonyms', suggested_synonyms
    ),
    JSON_OBJECT(),
    JSON_ARRAY(JSON_OBJECT('source_type', source, 'evidence', evidence_json)),
    JSON_ARRAY(),
    JSON_ARRAY(),
    JSON_ARRAY(source),
    confidence,
    'legacy-import-v1',
    'medium',
    'needs_review',
    FALSE,
    FALSE,
    'evidence-v1',
    COALESCE(created_at, NOW()),
    COALESCE(updated_at, NOW())
FROM semantic_business_suggestions
WHERE status = 'pending';
