-- First-stage semantic NL2SQL model tables.

CREATE TABLE IF NOT EXISTS semantic_datasources (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL DEFAULT 3306,
    `database` VARCHAR(128) NOT NULL,
    dialect VARCHAR(32) NOT NULL DEFAULT 'mysql',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    semantic_sql_enabled TINYINT(1) NOT NULL DEFAULT 0,
    semantic_sql_fallback_enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_semantic_datasource_endpoint (workspace_id, host, port, `database`),
    INDEX idx_semantic_datasource_workspace (workspace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_tables (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    physical_name VARCHAR(128) NOT NULL,
    business_name VARCHAR(128) NOT NULL,
    description TEXT NULL,
    synonyms JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    is_queryable TINYINT(1) NOT NULL DEFAULT 1,
    is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
    visible_role_ids JSON NOT NULL,
    visible_user_ids JSON NOT NULL,
    row_scope_enabled TINYINT(1) NOT NULL DEFAULT 1,
    row_scope_mode VARCHAR(20) NOT NULL DEFAULT 'required',
    row_scope_user_column_id INT NULL,
    row_scope_dept_column_id INT NULL,
    row_permission_mode VARCHAR(20) NOT NULL DEFAULT 'off',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_semantic_table_physical (workspace_id, datasource_id, physical_name),
    INDEX idx_semantic_tables_workspace (workspace_id),
    INDEX idx_semantic_tables_datasource (datasource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_columns (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    table_id INT NOT NULL,
    physical_table VARCHAR(128) NOT NULL,
    physical_name VARCHAR(128) NOT NULL,
    data_type VARCHAR(128) NOT NULL DEFAULT '',
    business_name VARCHAR(128) NOT NULL,
    description TEXT NULL,
    synonyms JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    is_queryable TINYINT(1) NOT NULL DEFAULT 1,
    is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
    visible_role_ids JSON NOT NULL,
    visible_user_ids JSON NOT NULL,
    is_primary_key TINYINT(1) NOT NULL DEFAULT 0,
    is_indexed TINYINT(1) NOT NULL DEFAULT 0,
    ordinal_position INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_semantic_column_physical (workspace_id, datasource_id, table_id, physical_name),
    INDEX idx_semantic_columns_workspace (workspace_id),
    INDEX idx_semantic_columns_datasource (datasource_id),
    INDEX idx_semantic_columns_table (table_id),
    INDEX idx_semantic_columns_name (physical_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_row_permissions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    table_id INT NOT NULL,
    subject_type VARCHAR(16) NOT NULL,
    subject_id VARCHAR(64) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    condition_json JSON NOT NULL,
    created_by VARCHAR(64) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX ix_semantic_row_perm_workspace_table (workspace_id, datasource_id, table_id),
    INDEX ix_semantic_row_perm_subject (workspace_id, subject_type, subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_metrics (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    business_name VARCHAR(128) NOT NULL,
    description TEXT NULL,
    formula TEXT NOT NULL,
    aggregation VARCHAR(32) NULL,
    table_id INT NOT NULL,
    column_id INT NULL,
    time_column_id INT NULL,
    default_grain VARCHAR(32) NULL,
    synonyms JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'suggested',
    is_queryable TINYINT(1) NOT NULL DEFAULT 1,
    is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
    visible_role_ids JSON NOT NULL,
    visible_user_ids JSON NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_semantic_metric_name (workspace_id, datasource_id, name),
    INDEX idx_semantic_metrics_workspace (workspace_id),
    INDEX idx_semantic_metrics_datasource (datasource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_relationships (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    left_table_id INT NOT NULL,
    right_table_id INT NOT NULL,
    left_column_id INT NOT NULL,
    right_column_id INT NOT NULL,
    relationship_type VARCHAR(32) NOT NULL DEFAULT 'many_to_one',
    confidence DOUBLE NOT NULL DEFAULT 0.5,
    status VARCHAR(20) NOT NULL DEFAULT 'suggested',
    is_queryable TINYINT(1) NOT NULL DEFAULT 1,
    description TEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_semantic_relationships_workspace (workspace_id),
    INDEX idx_semantic_relationships_datasource (datasource_id),
    INDEX idx_semantic_relationships_left_table (left_table_id),
    INDEX idx_semantic_relationships_right_table (right_table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_query_runs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NULL,
    session_id VARCHAR(128) NULL,
    question TEXT NOT NULL,
    semantic_enabled TINYINT(1) NOT NULL DEFAULT 0,
    fallback_used TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    error_type VARCHAR(64) NULL,
    intent_json JSON NULL,
    plan_json JSON NULL,
    `sql` TEXT NULL,
    legacy_sql TEXT NULL,
    referenced_tables JSON NOT NULL,
    row_count INT NOT NULL DEFAULT 0,
    execution_time_ms INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_semantic_query_runs_workspace (workspace_id),
    INDEX idx_semantic_query_runs_user (user_id),
    INDEX idx_semantic_query_runs_session (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS semantic_business_suggestions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    workspace_id VARCHAR(64) NOT NULL,
    datasource_id INT NOT NULL,
    object_type VARCHAR(20) NOT NULL,
    object_id INT NOT NULL,
    physical_name VARCHAR(128) NOT NULL,
    suggested_business_name VARCHAR(128) NOT NULL,
    suggested_description TEXT NULL,
    suggested_synonyms JSON NOT NULL,
    confidence DOUBLE NOT NULL DEFAULT 0.5,
    source VARCHAR(32) NOT NULL DEFAULT 'rule',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    evidence_json JSON NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    accepted_at DATETIME NULL,
    INDEX idx_semantic_business_suggestions_workspace (workspace_id),
    INDEX idx_semantic_business_suggestions_datasource (datasource_id),
    INDEX idx_semantic_business_suggestions_object (object_type, object_id),
    INDEX idx_semantic_business_suggestions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
